"""BayesIQ Dashboard — Generated by BayesIQ Data Audit Kit."""

import json
import os
import re

import pandas as pd
import plotly.express as px
import streamlit as st

st.set_page_config(page_title="BayesIQ Dashboard", layout="wide")


def _fmt_period(series):
    """Shorten period strings for compact x-axis labels."""
    def _shorten(s):
        # Weekly: "2025-12-01/2025-12-07" → "Dec 1"
        if "/" in s:
            s = s.split("/")[0]
        # Monthly: "2025-12" → "Dec '25"
        parts = s.split("-")
        if len(parts) >= 2:
            import calendar
            try:
                mon = calendar.month_abbr[int(parts[1])]
                if len(parts) == 2:
                    return f"{mon} '{parts[0][2:]}"
                return f"{mon} {int(parts[2])}"
            except (ValueError, IndexError):
                pass
        return s
    return series.map(_shorten)


def _humanize_label(col_name):
    """Convert snake_case column name to human-readable axis label."""
    return col_name.replace("_", " ").title()


def _polish_fig(fig, y_col, show_legend=True):
    """Apply consistent axis and legend polish to a Plotly figure."""
    fig.update_yaxes(title_text=_humanize_label(y_col))
    fig.update_xaxes(title_text="", tickangle=-30)
    if not show_legend:
        fig.update_layout(showlegend=False)

@st.cache_data
def load_data(path):
    """Load and clean the dataset from a file path."""
    if path.endswith('.parquet'):
        df = pd.read_parquet(path)
    else:
        df = pd.read_csv(path)

    if "timestamp" in df.columns:
        df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)

    # Remove near-duplicate rows
    dedup_cols = ["user_id", "account_id", "event_name", "timestamp", "plan_tier", "region", "acquisition_channel", "account_segment", "mrr", "expansion_amount", "session_duration", "churned_flag", "active_flag", "current_mrr", "prior_mrr"]
    before = len(df)
    df = df.drop_duplicates(subset=dedup_cols, keep='first')
    after = len(df)
    df.attrs["rows_deduped"] = before - after

    return df


@st.cache_data
def load_uploaded(file):
    """Load and clean a dataset from an uploaded file."""
    if file.name.endswith('.parquet'):
        df = pd.read_parquet(file)
    else:
        df = pd.read_csv(file)

    if "timestamp" in df.columns:
        df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)

    # Remove near-duplicate rows
    dedup_cols = ["user_id", "account_id", "event_name", "timestamp", "plan_tier", "region", "acquisition_channel", "account_segment", "mrr", "expansion_amount", "session_duration", "churned_flag", "active_flag", "current_mrr", "prior_mrr"]
    before = len(df)
    df = df.drop_duplicates(subset=dedup_cols, keep='first')
    after = len(df)
    df.attrs["rows_deduped"] = before - after

    return df


def main():
    st.title("BayesIQ Data Dashboard")

    st.sidebar.header("Data Source")
    uploaded_file = st.sidebar.file_uploader(
        "Upload CSV or Parquet",
        type=["csv", "parquet", "pq"],
        help="Drag and drop a file here, or click to browse."
    )
    default_path = "data/raw_month_3.csv"
    data_path = st.sidebar.text_input("Or enter file path", value=default_path)

    # Load from upload or path
    df = None
    if uploaded_file is not None:
        try:
            df = load_uploaded(uploaded_file)
        except Exception as e:
            st.error(f"Could not load uploaded file: {e}")
            return
    elif data_path:
        try:
            df = load_data(data_path)
        except Exception as e:
            st.error(f"Could not load dataset: {e}")
            return
    else:
        st.info("Upload a file or enter a dataset path in the sidebar to get started.")
        return

    # Auto-detect period: weekly for short datasets, monthly otherwise
    _period = "M"
    if "timestamp" in df.columns:
        _ts_range = df["timestamp"].max() - df["timestamp"].min()
        if _ts_range.days <= 45:
            _period = "W"

    # --- Column Role Wizard ---
    roles_file = os.path.join(os.path.dirname(__file__), "column_roles_resolved.json")
    saved_roles = {}
    if os.path.exists(roles_file):
        with open(roles_file) as _f:
            saved_roles = json.load(_f)

    ambiguous_cols = ["user_id", "account_id"]
    unresolved = [c for c in ambiguous_cols if c not in saved_roles]

    if unresolved:
        st.info("Some columns contain embedded numbers (e.g. \"5 Pack\", \"8 MILLIGRAM\"). Tell us how to use them.")
        with st.expander("Configure column roles", expanded=False):
            wizard_roles = {}
            st.markdown("**user_id** — e.g. USR-000001, USR-000002, USR-000003")
            user_id_role = st.radio(
                "Role for user_id",
                ['Use as filter (categorical)', 'Use as numeric multiplier', 'Ignore this column'],
                index=0,
                key="wizard_user_id",
                horizontal=True,
            )
            wizard_roles["user_id"] = {"role": user_id_role}
            if "multiplier" in user_id_role.lower():
                user_id_target = st.selectbox(
                    "Multiply against",
                    ["mrr", "expansion_amount", "session_duration", "churned_flag", "active_flag", "current_mrr", "prior_mrr"],
                    index=0,
                    key="wizard_user_id_target",
                )
                wizard_roles["user_id"]["multiply_against"] = user_id_target

            st.markdown("**account_id** — e.g. ACC-00001, ACC-00002, ACC-00003")
            account_id_role = st.radio(
                "Role for account_id",
                ['Use as filter (categorical)', 'Use as numeric multiplier', 'Ignore this column'],
                index=0,
                key="wizard_account_id",
                horizontal=True,
            )
            wizard_roles["account_id"] = {"role": account_id_role}
            if "multiplier" in account_id_role.lower():
                account_id_target = st.selectbox(
                    "Multiply against",
                    ["mrr", "expansion_amount", "session_duration", "churned_flag", "active_flag", "current_mrr", "prior_mrr"],
                    index=0,
                    key="wizard_account_id_target",
                )
                wizard_roles["account_id"]["multiply_against"] = account_id_target

            if st.button("Save column roles", type="primary"):
                saved_roles.update(wizard_roles)
                with open(roles_file, 'w') as _f:
                    json.dump(saved_roles, _f, indent=2)
                st.success("Column roles saved. Reloading...")
                st.rerun()

    # Apply resolved column roles
    for col_name, role_info in saved_roles.items():
        if col_name not in df.columns:
            continue
        role_str = role_info.get("role", "")
        if "multiplier" in role_str.lower():
            target = role_info.get("multiply_against")
            if target and target in df.columns:
                nums = df[col_name].astype(str).str.extract(r"(\d+(?:\.\d+)?)", expand=False).astype(float)
                derived_name = role_info.get("derived_metric_name", f"{target}_x_{col_name}")
                df[derived_name] = df[target] * nums
        elif "ordered" in role_str.lower() or "ordinal" in role_str.lower():
            sort_order = df[col_name].drop_duplicates().to_frame()
            sort_order["_sort"] = sort_order[col_name].astype(str).str.extract(r"(\d+(?:\.\d+)?)", expand=False).astype(float)
            sort_order = sort_order.sort_values("_sort")[col_name].tolist()
            df[col_name] = pd.Categorical(df[col_name], categories=sort_order, ordered=True)

    # --- Sidebar Filters ---
    st.sidebar.header("Filters")

    if "timestamp" in df.columns:
        min_date = df["timestamp"].min().date()
        max_date = df["timestamp"].max().date()
        date_range = st.sidebar.date_input(
            "Date Range",
            value=(min_date, max_date),
            min_value=min_date,
            max_value=max_date,
        )
        if len(date_range) == 2:
            df = df[(df["timestamp"].dt.date >= date_range[0]) &
                    (df["timestamp"].dt.date <= date_range[1])]

    if "event_name" in df.columns:
        event_name_opts = sorted(df["event_name"].dropna().unique().tolist())
        event_name_sel = st.sidebar.multiselect(
            "event_name",
            options=event_name_opts,
            default=event_name_opts,
        )
        df = df[df["event_name"].isin(event_name_sel)]

    if "plan_tier" in df.columns:
        plan_tier_opts = sorted(df["plan_tier"].dropna().unique().tolist())
        plan_tier_sel = st.sidebar.multiselect(
            "plan_tier",
            options=plan_tier_opts,
            default=plan_tier_opts,
        )
        df = df[df["plan_tier"].isin(plan_tier_sel)]

    if "region" in df.columns:
        region_opts = sorted(df["region"].dropna().unique().tolist())
        region_sel = st.sidebar.multiselect(
            "region",
            options=region_opts,
            default=region_opts,
        )
        df = df[df["region"].isin(region_sel)]

    if "acquisition_channel" in df.columns:
        acquisition_channel_opts = sorted(df["acquisition_channel"].dropna().unique().tolist())
        acquisition_channel_sel = st.sidebar.multiselect(
            "acquisition_channel",
            options=acquisition_channel_opts,
            default=acquisition_channel_opts,
        )
        df = df[df["acquisition_channel"].isin(acquisition_channel_sel)]

    if "account_segment" in df.columns:
        account_segment_opts = sorted(df["account_segment"].dropna().unique().tolist())
        account_segment_sel = st.sidebar.multiselect(
            "account_segment",
            options=account_segment_opts,
            default=account_segment_opts,
        )
        df = df[df["account_segment"].isin(account_segment_sel)]

    if "mrr" in df.columns:
        mrr_opts = sorted(df["mrr"].dropna().unique().tolist())
        mrr_sel = st.sidebar.multiselect(
            "mrr",
            options=mrr_opts,
            default=mrr_opts,
        )
        df = df[df["mrr"].isin(mrr_sel)]

    if "expansion_amount" in df.columns:
        expansion_amount_opts = sorted(df["expansion_amount"].dropna().unique().tolist())
        expansion_amount_sel = st.sidebar.multiselect(
            "expansion_amount",
            options=expansion_amount_opts,
            default=expansion_amount_opts,
        )
        df = df[df["expansion_amount"].isin(expansion_amount_sel)]

    if "churned_flag" in df.columns:
        churned_flag_opts = sorted(df["churned_flag"].dropna().unique().tolist())
        churned_flag_sel = st.sidebar.multiselect(
            "churned_flag",
            options=churned_flag_opts,
            default=churned_flag_opts,
        )
        df = df[df["churned_flag"].isin(churned_flag_sel)]

    if "active_flag" in df.columns:
        active_flag_opts = sorted(df["active_flag"].dropna().unique().tolist())
        active_flag_sel = st.sidebar.multiselect(
            "active_flag",
            options=active_flag_opts,
            default=active_flag_opts,
        )
        df = df[df["active_flag"].isin(active_flag_sel)]

    if "current_mrr" in df.columns:
        current_mrr_opts = sorted(df["current_mrr"].dropna().unique().tolist())
        current_mrr_sel = st.sidebar.multiselect(
            "current_mrr",
            options=current_mrr_opts,
            default=current_mrr_opts,
        )
        df = df[df["current_mrr"].isin(current_mrr_sel)]

    if "prior_mrr" in df.columns:
        prior_mrr_opts = sorted(df["prior_mrr"].dropna().unique().tolist())
        prior_mrr_sel = st.sidebar.multiselect(
            "prior_mrr",
            options=prior_mrr_opts,
            default=prior_mrr_opts,
        )
        df = df[df["prior_mrr"].isin(prior_mrr_sel)]

    st.sidebar.metric("Rows (filtered)", f"{len(df):,}")
    deduped = df.attrs.get("rows_deduped", 0)
    if deduped:
        st.sidebar.metric("Rows deduped", f"{deduped:,}")

    tabs = st.tabs(["Metrics", "Data Quality", "Raw Data"])

    with tabs[0]:
        st.header("Business Metrics")

        _compact = dict(height=260, margin=dict(l=40, r=20, t=40, b=30),
                        title_font_size=13,
                        legend=dict(orientation="h", y=-0.25, font=dict(size=10)))

        _dim_options = ["Topline", "plan_tier", "acquisition_channel", "region", "account_segment"]
        _sel_dim = st.radio("Dimension", _dim_options, index=0, horizontal=True, key="dim_radio")
        _dim_col = None if _sel_dim == "Topline" else _sel_dim
        _legend_shown = False

        # --- Row 1 ---
        r1c1, r1c2, r1c3 = st.columns(3)

        with r1c1:
            num_df = df[(df["churned_flag"] == 1)]
            den_df = df[(df["active_flag"] == 1)]
            if _dim_col and _dim_col in num_df.columns:
                num_dim = num_df.groupby([num_df["timestamp"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                den_dim = den_df.groupby([den_df["timestamp"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                ratio_dim = (num_dim / den_dim).stack().reset_index()
                ratio_dim.columns = ["period", _dim_col, "churn_rate"]
                ratio_dim["period"] = _fmt_period(ratio_dim["period"].astype(str))
                if ratio_dim.empty:
                    st.info("No data for Churn Rate.")
                else:
                    fig = px.line(ratio_dim, x="period", y="churn_rate", color=_dim_col, title="Churn Rate (%)", markers=True)
                    fig.update_layout(**_compact)
                    _polish_fig(fig, "churn_rate", show_legend=not _legend_shown)
                    _legend_shown = True
                    st.plotly_chart(fig, use_container_width=True)
            else:
                den_grouped = den_df.groupby(den_df["timestamp"].dt.to_period(_period)).size()
                num_grouped = num_df.groupby(num_df["timestamp"].dt.to_period(_period)).size().reindex(den_grouped.index, fill_value=0)
                ratio_df = (num_grouped / den_grouped).fillna(0).reset_index()
                ratio_df.columns = ["period", "churn_rate"]
                ratio_df["period"] = _fmt_period(ratio_df["period"].astype(str))
                if ratio_df.empty:
                    st.info("No data for Churn Rate.")
                else:
                    fig = px.line(ratio_df, x="period", y="churn_rate", title="Churn Rate (%)", markers=True)
                    fig.update_layout(**_compact)
                    _polish_fig(fig, "churn_rate")
                    st.plotly_chart(fig, use_container_width=True)

        with r1c2:
            metric_df = df
            if "current_mrr" not in metric_df.columns:
                st.warning("Column \"current_mrr\" not found — skipping MRR.")
            else:
                if _dim_col and _dim_col in metric_df.columns:
                    grouped = metric_df.groupby([metric_df["timestamp"].dt.to_period(_period), _dim_col])["current_mrr"].sum().reset_index()
                    grouped.columns = ["period", _dim_col, "mrr"]
                    grouped["period"] = _fmt_period(grouped["period"].astype(str))
                    fig = px.bar(grouped, x="period", y="mrr", color=_dim_col, title="MRR ($)", barmode="group")
                else:
                    grouped = metric_df.groupby(metric_df["timestamp"].dt.to_period(_period))["current_mrr"].sum().reset_index()
                    grouped.columns = ["period", "mrr"]
                    grouped["period"] = _fmt_period(grouped["period"].astype(str))
                    fig = px.bar(grouped, x="period", y="mrr", title="MRR ($)")
                fig.update_layout(**_compact)
                _polish_fig(fig, "mrr", show_legend=not _legend_shown and _dim_col is not None)
                if _dim_col: _legend_shown = True
                st.plotly_chart(fig, use_container_width=True)

        with r1c3:
            num_df = df
            den_df = df
            if _dim_col and _dim_col in num_df.columns:
                num_dim = num_df.groupby([num_df["timestamp"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                den_dim = den_df.groupby([den_df["timestamp"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                ratio_dim = (num_dim / den_dim).stack().reset_index()
                ratio_dim.columns = ["period", _dim_col, "nrr"]
                ratio_dim["period"] = _fmt_period(ratio_dim["period"].astype(str))
                if ratio_dim.empty:
                    st.info("No data for NRR.")
                else:
                    fig = px.line(ratio_dim, x="period", y="nrr", color=_dim_col, title="NRR (%)", markers=True)
                    fig.update_layout(**_compact)
                    _polish_fig(fig, "nrr", show_legend=not _legend_shown)
                    _legend_shown = True
                    st.plotly_chart(fig, use_container_width=True)
            else:
                den_grouped = den_df.groupby(den_df["timestamp"].dt.to_period(_period)).size()
                num_grouped = num_df.groupby(num_df["timestamp"].dt.to_period(_period)).size().reindex(den_grouped.index, fill_value=0)
                ratio_df = (num_grouped / den_grouped).fillna(0).reset_index()
                ratio_df.columns = ["period", "nrr"]
                ratio_df["period"] = _fmt_period(ratio_df["period"].astype(str))
                if ratio_df.empty:
                    st.info("No data for NRR.")
                else:
                    fig = px.line(ratio_df, x="period", y="nrr", title="NRR (%)", markers=True)
                    fig.update_layout(**_compact)
                    _polish_fig(fig, "nrr")
                    st.plotly_chart(fig, use_container_width=True)

        # --- Row 2 ---
        r2c1, r2c2, r2c3 = st.columns(3)

        with r2c1:
            metric_df = df
            if _dim_col and _dim_col in metric_df.columns:
                grouped = metric_df.groupby([metric_df["timestamp"].dt.to_period(_period), _dim_col]).size().reset_index()
                grouped.columns = ["period", _dim_col, "active_users"]
                grouped["period"] = _fmt_period(grouped["period"].astype(str))
                fig = px.bar(grouped, x="period", y="active_users", color=_dim_col, title="Active Users", barmode="group")
            else:
                grouped = metric_df.groupby(metric_df["timestamp"].dt.to_period(_period)).size().reset_index()
                grouped.columns = ["period", "active_users"]
                grouped["period"] = _fmt_period(grouped["period"].astype(str))
                fig = px.bar(grouped, x="period", y="active_users", title="Active Users")
            fig.update_layout(**_compact)
            _polish_fig(fig, "active_users", show_legend=not _legend_shown and _dim_col is not None)
            if _dim_col: _legend_shown = True
            st.plotly_chart(fig, use_container_width=True)

        with r2c2:
            metric_df = df
            if "expansion_amount" not in metric_df.columns:
                st.warning("Column \"expansion_amount\" not found — skipping Expansion Revenue.")
            else:
                if _dim_col and _dim_col in metric_df.columns:
                    grouped = metric_df.groupby([metric_df["timestamp"].dt.to_period(_period), _dim_col])["expansion_amount"].sum().reset_index()
                    grouped.columns = ["period", _dim_col, "expansion_revenue"]
                    grouped["period"] = _fmt_period(grouped["period"].astype(str))
                    fig = px.bar(grouped, x="period", y="expansion_revenue", color=_dim_col, title="Expansion Revenue ($)", barmode="group")
                else:
                    grouped = metric_df.groupby(metric_df["timestamp"].dt.to_period(_period))["expansion_amount"].sum().reset_index()
                    grouped.columns = ["period", "expansion_revenue"]
                    grouped["period"] = _fmt_period(grouped["period"].astype(str))
                    fig = px.bar(grouped, x="period", y="expansion_revenue", title="Expansion Revenue ($)")
                fig.update_layout(**_compact)
                _polish_fig(fig, "expansion_revenue", show_legend=not _legend_shown and _dim_col is not None)
                if _dim_col: _legend_shown = True
                st.plotly_chart(fig, use_container_width=True)

        with r2c3:
            st.markdown("##### KPI Summary")
            st.markdown(f"**Total Rows:** {len(df):,}")
            if "timestamp" in df.columns:
                _min = df["timestamp"].min().strftime("%Y-%m-%d")
                _max = df["timestamp"].max().strftime("%Y-%m-%d")
                st.markdown(f"**Date Range:** {_min} to {_max}")
            if "current_mrr" in df.columns:
                _total_mrr = df["current_mrr"].sum()
                st.markdown(f"**Total MRR:** ${_total_mrr:,.0f}")

    with tabs[1]:
        st.header("Data Quality Summary")
        st.metric("Total Issues Found", 4)

        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Critical", 0)
        col2.metric("High", 4)
        col3.metric("Medium", 0)
        col4.metric("Low", 0)

        st.info("This dashboard applies automatic cleaning: value canonicalization and near-duplicate deduplication. The issues below were detected in the raw data before cleaning.")

        st.subheader("Findings")
        st.markdown("**1. [HIGH]** active_users misreported for 2025-12 (off by -434.2%) (1 rows)")
        st.markdown("**2. [HIGH]** churn_rate misreported for 2025-12 (off by +84.4%) (1 rows)")
        st.markdown("**3. [HIGH]** Near-duplicate rows detected (102 rows)")
        st.markdown("**4. [HIGH]** Null values in required column: user_id (40 rows)")

    with tabs[2]:
        st.header("Raw Data")
        st.dataframe(df.head(1000), use_container_width=True)


if __name__ == "__main__":
    main()
